name: je reponds fraternite
author: adfinitas
url:
url_iraiser:
url_iraiser_donner:
iraiser_counter_user_api:
iraiser_counter_user_pass:
collections:
  posts:
    output: true
  drafts:
    output: true